### ISSUE TITLE
第14页.text-cols为什么会出现首字母放大下沉

### ISSUE THREAD

**Issue by guanpengchn** [ksky521/nodeppt#235]
| Executable | Version |
| ---: | :--- |
| `node --version` | 8.9 |
| `npm --version`  | 6.4.1 |
| `nodeppt -v` | 2.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

链接如下，在css中未找到相关定义，如果不需要这个首字母放大下沉怎么办？

https://nodeppt.js.org/#slide=14

**Comment by alili** [comment]
这段样式位于 `/assets/scss/_typography.scss` line 298

我用如下代码覆盖了样式
``` css
.text-cols p:first-child:first-letter {
  float: none !important;
  font-weight: inherit !important;
  line-height: 1 !important;
  font-size: inherit !important;
  margin: auto !important;
}
```
