### ISSUE TITLE
如何配置slide中 字体的大小和样式？

### ISSUE THREAD

**Issue by nigangkaka** [ksky521/nodeppt#258]
1. 请问有没有哪些配置可以修改字体的大小，比方说H1，或者是列表的字体大小可以定制？
2. H1 Title的英文字体，字母之间有空隙太大了，这个可以定制修改吗？

**Comment by ksky521** [comment]
可以在头部声明的时候加上自定义的 css

**Comment by roymina** [comment]
```css
html,
body,
input,
select,
textarea {
  font-family: 'Microsoft YaHei' !important;
}
```
